version: '3.7'
services:
  streetmerchant:
    image: jinxcappa/streetmerchant
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 10s
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    cap_add: 
      - SYS_ADMIN
    env_file: ./.env